plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlinx-serialization'
}

ext {
    extName = 'CuuTruyen2'
    pkgNameSuffix = 'vi.cuutruyen'
    extClass = '.CuuTruyen2'
    extVersionCode = 1
    isNsfw = false
    PLUGIN_CLASS_NAME = 'eu.kanade.tachiyomi.extension.vi.cuutruyen.CuuTruyen2'
    EXTENSION_CLASS_NAME = 'eu.kanade.tachiyomi.extension.vi.cuutruyen.CuuTruyen2'
    SITE_MULTISRC = 'cuutruyen'
    IS_MULTISRC = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    compileOnly libs.tachiyomi.lib
}
